clusterName: titanedge-nexus-dev
clusterEndpoint: https://935AFB997D1C335629544344E8E24151.gr7.us-east-1.eks.amazonaws.com

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole-${AWS_ACCOUNT_ID}

replicas: 1

controller:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  env:
    - name: CLUSTER_NAME
      value: titanedge-nexus-dev
    - name: CLUSTER_ENDPOINT
      value: https://935AFB997D1C335629544344E8E24151.gr7.us-east-1.eks.amazonaws.com

webhook:
  enabled: false
