name: Conftest

on: [push, pull_request]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run Conftest on Kubernetes manifests
        uses: docker://openpolicyagent/conftest:v0.55.0
        with:
          args: test --policy kubernetes/policy/ kubernetes/
