name: Conftest

on: [push, pull_request]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Conftest on Kubernetes manifests
        uses: instrumenta/conftest-action@v1.6.0
        with:
          files: kubernetes/
          policy: kubernetes/policy/
