name: Conftest

on: [push, pull_request]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run Conftest on Kubernetes manifests
        uses: instrumenta/conftest-action@v1
        with:
          files: "kubernetes/"
          policy: "kubernetes/policy/"
