name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run Trivy on Terraform
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "terraform/"
          format: "sarif"
          output: "trivy-iac.sarif"
      - uses: github/codeql-action/upload-sarif@c7f9125735019aa87c307053cc6e3b0c6ccd4f8f
        with:
          sarif_file: "trivy-iac.sarif"
      - name: Run Trivy on Kubernetes manifests
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "kubernetes/"
          format: "sarif"
          output: "trivy-k8s.sarif"
      - uses: github/codeql-action/upload-sarif@c7f9125735019aa87c307053cc6e3b0c6ccd4f8f
        with:
          sarif_file: "trivy-k8s.sarif"
