name: Trivy Scan

on:
  push:

  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read
  security-events: write

jobs:
  scan-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Trivy on Terraform (IaC)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'config'
          scan-ref: 'terraform/'
          format: 'sarif'
          output: 'trivy-iac.sarif'
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-iac.sarif'

  scan-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Trivy on Kubernetes Manifests
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'config'
          scan-ref: 'kubernetes/'
          format: 'sarif'
          output: 'trivy-k8s.sarif'
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-k8s.sarif'
